baseurl = "https://strconv.com"
languageCode = "en-us"
title = "strconv"
theme = "hugo-coder"
publishDir = "."
paginate = 10
googleAnalytics = "UA-143191829-1"
disableKinds = ["RSS"]
canonifyurls = true
pygmentsCodefences = true
pygmentsStyle = "dracula"

[params]
    description = "strconv - 我是一个Golang模块"
    keywords = "golang,go"
    footercontent = "我是一个Golang模块."

    dateformat = "January 2, 2006"

    hideCopyright = false

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 10

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4